name: Build Themis

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.65.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.13.6
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_program:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: metaplex-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: metaplex-foundation/actions/cache-programs@v1

      - name: Download binary
        run: |
          bash <(curl -sSf https://raw.githubusercontent.com/metaplex-foundation/themis/main/scripts/install.sh)
          echo $(themis -V)
