name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "programs/**/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo "Changes detected in src/ on main branch"
